# Generated by Django 5.2.4 on 2025-07-29 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'ordering': ['address'], 'verbose_name': 'Место', 'verbose_name_plural': 'Места'},
        ),
        migrations.AlterField(
            model_name='place',
            name='address',
            field=models.CharField(help_text='Адрес места (например, улица и дом)', max_length=255, unique=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='place',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Координаты в формате [широта, долгота]', null=True, verbose_name='Координаты'),
        ),
        migrations.AlterField(
            model_name='place',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Когда координаты были обновлены', verbose_name='Дата обновления'),
        ),
    ]
