FROM node:16-bullseye

WORKDIR /frontend
RUN apt-get update && \
    apt-get install -y python3 make g++ && \
    rm -rf /var/lib/apt/lists/*

COPY package*.json ./
RUN npm ci --include=dev

COPY bundles-src ./bundles-src

CMD ["npx", "parcel", "build", "bundles-src/index.js", "--dist-dir", "bundles", "--public-url", "./"]
