services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: starburger
      POSTGRES_USER: starburger
      POSTGRES_PASSWORD: burgerpass
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 star_burger.wsgi:application
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
      - ./bundles:/app/bundles

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./bundles:/frontend/bundles
    command: ["npm", "run", "build"]

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/var/www/static
      - media_volume:/var/www/media
      - ./bundles:/var/www/frontend

volumes:
  pgdata:
  static_volume:
  media_volume:
