# Generated by Django 5.2.4 on 2025-07-28 13:09

from django.db import migrations


def fill_orderitem_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.select_related('product'):
        item.price = item.product.price
        item.save(update_fields=['price'])


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_orderitem_price'),
    ]

    operations = [
        migrations.RunPython(fill_orderitem_prices, migrations.RunPython.noop),
    ]
