# Generated by Django 5.2.4 on 2025-07-28 13:19

from django.db import migrations


def fill_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.filter(price=0):
        item.price = item.product.price
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0041_auto_20250728_1309'),
    ]

    operations = [
        migrations.RunPython(fill_prices, reverse_code=migrations.RunPython.noop),
    ]
