# Generated by Django 5.2.4 on 2025-07-28 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20250728_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('unprocessed', 'Необработанный'), ('confirmed', 'Подтвержден'), ('preparing', 'Готовится'), ('delivering', 'Доставляется'), ('completed', 'Завершен')], db_index=True, default='unprocessed', max_length=20, verbose_name='Статус'),
        ),
    ]
