# Generated by Django 5.2.4 on 2025-07-28 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_called_at_order_delivered_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('electronic', 'Картой')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
