# Generated by Django 5.2.4 on 2025-07-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_cooking_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='coordinates',
            field=models.JSONField(blank=True, help_text='Широта и долгота в формате [lat, lon]', null=True, verbose_name='координаты'),
        ),
    ]
